---
- name: install EPEL
  yum: name=http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- name: install basic packages
  yum: name={{ item }} state=present
  with_items:
    - tmux
    - vim-enhanced
    - sysstat
    - wget
    - telnet
    - unzip
    - mailx
    - hdparm
    - ncdu
    - smartmontools
    - lsof
    - iftop
    - iotop
    - hdparm
    - virt-what
    - git
